version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: $APP_NAME
    ports:
      - "9000:80"
    volumes:
      - ..:/var/www/${APP_NAME}:delegated
      - ../../framework:/var/www/framework:delegated
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    environment:
      LANG: "C.UTF-8"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  redis:
    image: redis:alpine
